completed buttons
hemanshthakur/Component-library pull request #4
Opened 2022-02-07 03:35 UTC by hemanshthakur

![icon-showcase](https://user-images.githubusercontent.com/85496045/152720418-9c7cb1c6-c642-4dac-af4e-7ce9f8ec85e7.png)

2022-02-07 11:26 UTC, Bibin-Antony requested changes

2022-02-07 11:26 UTC, Bibin-Antony commented on containers/css/buttons.css
> +:root{
add this to your root style file and import it.

2022-02-08 05:05 UTC, hiteshverma27 commented on containers/css/buttons.css
> +    box-shadow: 0 0 1rem  var(--shader);
Try to make utility class for things like this for generalized class names
`.bg-secondary{
      background-color: var(--secondary-color)
      }`

2022-02-08 05:06 UTC, hiteshverma27 approved these changes

2022-02-08 12:11 UTC, Bibin-Antony approved these changes

2022-02-08 13:31 UTC, merged