completed : Cards
hemanshthakur/Component-library pull request #5
Opened 2022-02-07 05:20 UTC by hemanshthakur

![Uploading cards-showcase.png…]()

2022-02-07 11:27 UTC, Bibin-Antony requested changes

2022-02-07 11:27 UTC, Bibin-Antony commented on containers/css/cards.css
> +:root{
move it to the root file and import it into this file

2022-02-08 05:19 UTC, hiteshverma27 approved these changes

2022-02-08 11:49 UTC, Bibin-Antony approved these changes

2022-02-08 12:30 UTC, merged